---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04

suites:
  - name: default
    data_bag_item: '/test/integration/data_bags'
    run_list:
      - recipe[chefkata::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
      chefkata:
        builder: 'Test Kitchen'
